version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - .:/app
      - garden_uploads:/app/app/static/uploads
    environment:
      - POSTGRES_USER=garden_user
      - POSTGRES_PASSWORD=mygarden
      - POSTGRES_DB=garden_db
      - POSTGRES_HOST=db
      - DATABASE_URL=postgresql://garden_user:mygarden@db:5432/garden_db
      - PYTHONPATH=/app
      - DEBUG=${DEBUG:-false}
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --reload

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres  # Changed to postgres to ensure proper initialization
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: postgres -c 'max_connections=100' -c 'shared_buffers=128MB'

volumes:
  postgres_data:
  garden_uploads: