"""add_image_model_with_associations

Revision ID: a9cb2876c060
Revises: c2b4b02ab523
Create Date: 2025-03-10 18:36:18.190641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9cb2876c060'
down_revision = 'c2b4b02ab523'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###