"""remove_unneeded_fields_from_seed_packet

Revision ID: c2b4b02ab523
Revises: add_seed_packet_details
Create Date: 2025-03-08 22:48:43.568347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b4b02ab523'
down_revision = 'add_seed_packet_details'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seed_packets', 'expiration_date')
    op.drop_column('seed_packets', 'package_weight')
    op.drop_column('seed_packets', 'fertilizer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seed_packets', sa.Column('fertilizer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('seed_packets', sa.Column('package_weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('seed_packets', sa.Column('expiration_date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###